name: CompatHelper

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.2.0]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.add(Pkg.PackageSpec(name = "https://git", url = "", rev = ""))'
      - name: CompatHelper.main
        env:
          AUTOMERGE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JULIA_DEBUG: CompatHelper
        run: julia -e 'using CompatHelper; CompatHelper.main(; suggest_missing_compat_entries = false)'
