coverage:
  status:
    project:
      # no leniency on `main`
      main:
        branches:
          - main
          - gh-readonly-queue/main/*
        target: 100%
      # on PRs, we allow some leniency since integration tests haven't run yet
      default:
        target: 98%
